name: gis-public-policy
channels:
  - conda-forge
dependencies:
  - altair=4.1.*
  - vega=3.2.*
  - pandas=1.*
  - jupyterlab=2.1.*
  - geopandas=0.7.*
  - matplotlib=3.2.*
  - descartes=1.1.*
  - geoplot=0.4.*
  - pip=20.*
  - pip:
    - census-data-downloader=0.0.26
